services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  fd-frontend:
    build: 
      context: './dir'
      dockerfile: 'frontend/dockerfile'
      image: 