services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: fd_db
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
    ports:
      - "5433:5433"
  be_fastapi:
    build:
      context: fd-backend-fastapi
      dockerfile: ./dockerfile
    container_name: fd_fastapi_backend
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    env_file:
      - .env
    restart: "no"
    depends_on:
      - postgres
  fe_react:
    build:
      context: fd-frontend-react
      dockerfile: ./dockerfile
    container_name: fd_react_frontend
    environment:
      PORT: 3000
    ports:
      - '3000:80'
    env_file:
      - .env
    restart: "no"
